### ISSUE TITLE
After setting Chinese characters in the cell, the file cannot be opened using Excel and is corrupted.

### ISSUE THREAD

**Issue by Polors** [troldal/OpenXLSX#292] opened 2024-11-14 08:15 UTC
![Snipaste_2024-11-14_16-11-31](https://github.com/user-attachments/assets/e287dcca-6937-4c55-b413-88820ca41d19)
I tried to use Openxlsx to add Chinese words in the cells. The code can be compiled successfully and can be executed, but when I double-clicked to open demo01.xlsx using Microsoft Excel, the file was corrupted. After clicking OK, Chinese words could not be displayed normally. The compiler I used is VS2019, 32-bit. The file save type is the default Utf-8. Please help me!
![Snipaste_2024-11-14_16-14-42](https://github.com/user-attachments/assets/c44d8563-2188-4c35-9056-dee9ff206277)

**Comment by aral-matrix** [comment] 2024-11-14 23:20
Please have a look here: https://github.com/troldal/OpenXLSX/issues/280 where the same issue was discussed and resolved. Chances are that your source code file is not saved in Unicode, or that you somehow use a build environment in which boost::nowide is not enabled.

**Comment by Polors** [comment] 2024-11-15 07:22
I checked whether nowide was used as you said, and then re-ran Demo4 in the source code without making any changes. Chinese characters were still garbled.
![111](https://github.com/user-attachments/assets/83302586-9271-4ce5-b622-6651ed533ce1)
I am sure that the source code file of demo4 is saved using Utf-8.
![222](https://github.com/user-attachments/assets/4feab63e-e3ad-4bd6-a87f-549b7c5262c3)
Also, when I compiled, I switched the property page to multi-byte character set or Unicode character set, but it didn't work.

In addition, I did not do anything. I pulled the source code from git and used Cmake to build and generate it. The build environment is: VS2019, win32 (I also tested Vs2019 x64 and there was no difference)
![444](https://github.com/user-attachments/assets/853d21b5-8afe-4af2-9290-7a81215c64a4)

Do I need to re-save all the source code of OpenXLSX in Utf-8 format?
![555](https://github.com/user-attachments/assets/08e8c78a-d6dc-4113-b0f7-d679382360ab)
Please help me！

**Comment by Polors** [comment] 2024-11-15 09:03
I have retested Demo1 and confirmed that nowide is used. Chinese can be output normally, but under certain conditions, compilation warnings and runtime errors appear. Here are my preliminary test conclusions:
![111](https://github.com/user-attachments/assets/010b90f4-de9d-4b2e-a9bb-b813cc937b6d)

Conclusion: The garbled characters are related to the number of Chinese punctuation marks used. Using an odd number of punctuation marks, such as Chinese exclamation marks ("!") and Chinese commas (",") will trigger this problem. It manifests as encoding warnings during compilation and garbled characters in the terminal during runtime. When I use an even number, it behaves normally. For example, I use 3 Chinese exclamation marks ("!") and 3 Chinese commas (","), and they can be displayed normally. Of course, this also tests the use of Chinese periods (". "), and finds that consecutive Chinese periods (". ") are regarded as one, which also meets the above odd and even number rules. For example: [. . . ! . . ! ] is regarded as 4, that is, an even number of Chinese symbols. More other symbols are yet to be tested.....

When there are an odd number of Chinese symbols and they are at the end of the string, the compiler even reports an error, as follows:
![222](https://github.com/user-attachments/assets/05a36857-35a5-4b45-8eb5-699f6356bae4)

**Comment by aral-matrix** [comment] 2024-11-15 15:13
Thank you for the further tests - I was on a day trip & will have a look tomorrow at the latest, but in general I was going to suggest we try and do failure tree isolation:
* I will send you a Demo4.xlsx encoded by a Demo4 compiled on Linux, and you can confirm whether or not that opens correctly, and if it does, then unzip it and do a recursive diff on the workbook XML files compared to the ones Demo4 produces on your system. Hopefully, from the differences, we can deduce where the encoding error happens
* With your further tests, I suspect that there might be either an encoding error in the Unicode support when saving your source files, or a decoding error for these specific characters in your version of MS Office (less likely). In order to confirm this, again, a look at the XML files of a workbook that generates an Office error message will help, and also to understand how the correct encoding of those special characters should look like

I don't use Windows myself, so the amount of testing I can do is limited to analyzing the XML and providing you with incremental differences to test for whether or not the error persists.

**Comment by Polors** [comment] 2024-11-18 00:42
> 感谢您进行进一步的测试 - 我正在进行一日游，最迟明天就会去看看，但总的来说，我建议我们尝试进行故障树隔离：
> 
> * 我将向您发送一个由 Linux 上编译的 Demo4 编码的 Demo4.xlsx，您可以确认它是否能正确打开，如果能，请解压缩它并对工作簿 XML 文件与 Demo4 在您的系统上生成的文件进行比较。希望从差异中，我们可以推断出编码错误发生的位置
> * 通过进一步的测试，我怀疑在保存源文件时 Unicode 支持可能存在编码错误，或者您的 MS Office 版本中存在这些特定字符的解码错误（可能性较小）。为了再次确认这一点，查看生成 Office 错误消息的工作簿的 XML 文件将有所帮助，同时也了解这些特殊字符的正确编码应该是什么样的
> 
> 我自己不使用 Windows，所以我能做的测试仅限于分析 XML 并为您提供增量差异以测试错误是否仍然存在。

Thank you for your attention to this issue. My email address is: cdqdahaoren@gmail.com. Please send the demo4 file encoded under Linux to me.

**Comment by aral-matrix** [comment] 2024-11-18 08:41
[Demo04.xlsx](https://github.com/user-attachments/files/17797208/Demo04.xlsx)
Attached is as generated by my system ```Demo04.xlsx``` for you to test. Apologies for the delay, I had a chance to join a day trip on a freight ship yesterday, so I didn't look at the computer :)

**Comment by Polors** [comment] 2024-11-18 12:21
> [Demo04.xlsx](https://github.com/user-attachments/files/17797208/Demo04.xlsx) 附件是我系统生成的`Demo04.xlsx`，供您测试。抱歉回复晚了，昨天我参加了货船一日游，所以没看电脑 :)



That's ok, glad you had a good weekend！I am glad that you can answer my question. I tried the Excel file you sent me and it worked without any problem. I used unzip to unzip and compared the files. It turned out to be an encoding problem. As I said above, when the number of my Chinese punctuation marks is an odd number, it has an encoding problem. The encoding problem can be clearly observed using WInHex. The strange thing is that when I set the number of Chinese punctuation marks to an even number, it has no problem. This is very troublesome.

![111](https://github.com/user-attachments/assets/73898c73-03d7-483c-8884-d96f42e4a6bf)
![222](https://github.com/user-attachments/assets/857788b3-7f02-4b9a-9285-d9bb7eee13a0)
![333](https://github.com/user-attachments/assets/57ed6e1c-90c1-4a95-933b-3b47abc05305)
This is the file I generated by running it directly。
[Demo04.xlsx](https://github.com/user-attachments/files/17800056/Demo04.xlsx)
Tomorrow I will try to compile it under Linux to see if there is any problem.

**Comment by aral-matrix** [comment] 2024-11-18 19:17
So - since we know that the generated Demo04.xlsx has an encoding problem, I can think of three remaining error locations. But first, for clarification, may I ask:
* Is my understanding correct that Demo04.xlsx contains an odd number of chinese punctuation marks, namely ```，``` or (hex) ```EFBC8C```, thereby triggering the error?

Where I can see the error originating:
1) an encoding error when the source file is saved to disk in your text editor (possibly reversible encoding error, so that the same text editor also correctly displays the file again), which then leads to a faulty string.
You can exclude this by compiling the Demo4.cpp from the repository without ever opening / saving it - if the resulting file is still corrupted, this is not the reason

2) the gcc compiler incorrectly reading the UTF-8 encoding from the Demo4.cpp source file - I am not entirely sure how to best debug this - possibly by excluding the other two potential root causes

3) an error when storing the value to a ```std::string``` (possibly in the ```std::string``` implementation itself) on your compiler version.
You can exclude / confirm this by testing the following program:
```
#include <cstdint>  // uint8_t
#include <iostream>
#include <string>

int main()
{
	std::string s = "你好，世界!";
	std::cout << "s is \"" << s << "\"" << std::endl;

	const uint8_t * c = reinterpret_cast< const uint8_t * >( s.c_str() );
	std::cout << "Bytes of s are:" << std::endl;
	for( size_t i = 0; s.c_str()[ i ] != 0; ++i )
		std::cout << "[ " << i << "] = 0x" << std::hex << static_cast< int >( static_cast< uint8_t >( s.c_str()[ i ] ) ) << std::dec << std::endl;

	return 0;
}
```

The output should have the correct byte sequence of the UTF-8:
```
s is "你好，世界!"
Bytes of s are:
[ 0] = 0xe4
[ 1] = 0xbd
[ 2] = 0xa0
[ 3] = 0xe5
[ 4] = 0xa5
[ 5] = 0xbd
[ 6] = 0xef
[ 7] = 0xbc
[ 8] = 0x8c
[ 9] = 0xe4
[ 10] = 0xb8
[ 11] = 0x96
[ 12] = 0xe7
[ 13] = 0x95
[ 14] = 0x8c
[ 15] = 0x21
```

**Comment by Polors** [comment] 2024-11-19 07:25
![111](https://github.com/user-attachments/assets/c7492a21-aeb4-43e1-b18b-e24951f52979)
Thank you very much for your reply. I debugged the code again and found that the encoding problem did occur at the [string] stage. It should be related to the compiler I used. As we all know, VisualStudio's encoding of Chinese is terrible. I will try to find a solution later. Thank you again for your patience. I think this issue can be closed.

**Comment by Polors** [comment] 2024-11-19 07:41
![222](https://github.com/user-attachments/assets/c52d00c5-d00c-48b0-9785-fd98cb386913)
I solved this problem. The root of the problem is the compiler. You need to add the /utf-8 compile option in the command line. I learned that strings contain three character sets from storage to printing.
1. Source character set /source-charset in MSVC
2. Execution character set /execution-charset in MSVC
3. Parsing character set When you finally want to restore and display these binary byte encodings, you need to use it. For example, when you display the previous str to the console through printf(), this printf() will parse these byte encodings according to the parsing character set and find the specified characters to display.

These three character sets need to be kept consistent to avoid garbled characters. You can use the /utf-8 option to specify the source character set and execution character set as character sets encoded with UTF-8. It is equivalent to specifying /source-charset:utf-8 /execution-charset:utf-8 on the command line.
Now, it's normal.

**Comment by aral-matrix** [comment] 2024-11-19 10:08
I am glad to hear you were able to solve the issue - and thank you very much for posting the solution here for "archiving purposes" :) This will help if someone else runs into the same problem.
Happy coding! If you don't do it, I will close this issue as resolved in a bit.

**Closed** 2024-12-15 23:05 UTC
Labels: resolved
