### ISSUE TITLE
Path does not exist in zip archive (xl/xl/worksheets/sheet1.xml)

### ISSUE THREAD

**Issue by Mo1son** [troldal/OpenXLSX#297] opened 2024-11-17 09:16 UTC
I have created a xlsx file using python's pandas module, and the code was as follows:
![image](https://github.com/user-attachments/assets/3a891152-2aec-4737-8932-00f7215250df)
After that, I was going to open it with OpenXLSX:
![image](https://github.com/user-attachments/assets/dc588182-d0f2-4878-b589-9c4bfd7cfefd)
However, some errors occurred and the prompts were as follows:
![image](https://github.com/user-attachments/assets/de8e5f6b-ab92-4396-bfc0-a3c6be3f2d3b)
I found the zip of xlsx and opened it, and then I found the reasons：
The correct path should be "a.xlsx\xl\worksheets\sheet1.xml" (Ignoring the previous path).
However, the OpenXLSX libarary  misjudged the file path as "a.xlsx\xl\xl\worksheets\sheet1.xml" (one more "\xl").
So, it failed to open the work sheets.
Hence, I checked and debugged the source code of OpenXLSX libarary.
![image](https://github.com/user-attachments/assets/8fce9e82-a3d8-414e-8a07-ba6fd27765f8)
At this part of code, the program got the path "\xl\xl\worksheets\sheet1.xml", which was not correct.
How can I fix this problem?
Thank you in advance for your time and help. I really appreciate the work you've put into this project!

**Comment by aral-matrix** [comment] 2024-11-17 19:42
Could you please unzip your test XLSX file and check ```xl/_rels/workbook.xml.rels```?

I am pretty sure your file contains this entry:
```
	<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="xl/worksheets/sheet1.xml"/>
```
(the Relationship Id may differ)

This is - to my knowledge - an invalid ```Target``` path. The ```Target``` should be either a relative path from ```xl/```, so for example ```Target="worksheets/sheet1.xml"```, or an absolute path in the workbook, which must start with a ```/``` - so for example ```Target="/xl/worksheets/sheet1.xml"```.

Your python library seems to produce an invalid relationship target path, which also can not be correctly opened in LibreOffice. I accordingly suggest you open a ticket against your python library.

**Comment by aral-matrix** [comment] 2024-12-15 00:44
Duplicate of #306

**Comment by aral-matrix** [comment] 2024-12-15 02:44
Should be fixed in the development-aral branch with https://github.com/troldal/OpenXLSX/commit/5dfa70a6e462cdaf6efe7758dde0957b3cab3970

Once I am reasonably confident I didn't break anything else, I will merge it into the main branch.

**Comment by aral-matrix** [comment] 2024-12-19 20:50
Patch has been merged into main branch. Closing as resolved.

**Closed** 2024-12-19 20:50 UTC
Labels: bug, testing, resolved
