### ISSUE TITLE
XLWorkbook setSheetIndex wrong

### ISSUE THREAD

**Issue by WuyangPeng** [troldal/OpenXLSX#106] opened 2021-10-14 10:51 UTC
if (index == std::distance(xmlDocument().document_element().child("sheets").children().begin(),
                               std::find_if(xmlDocument().document_element().child("sheets").children().begin(),
                                            xmlDocument().document_element().child("sheets").children().end(),
                                            [&](const XMLNode& item) { return sheetName == item.attribute("name").value(); })))
        return;

That's right index - 1

**Comment by troldal** [comment] 2022-06-26 15:55
Not sure what the issue is here, so I'm closing it.

**Closed by troldal** 2022-06-26 15:55 UTC

**Comment by WuyangPeng** [comment] 2022-06-27 11:29
i mean in function  void XLWorkbook::setSheetIndex(const std::string& sheetName, unsigned int index)

if (index == std::distance(xmlDocument().document_element().child("sheets").children().begin(),

should be

if (index - 1 == std::distance(xmlDocument().document_element().child("sheets").children().begin(),

**Comment by troldal** [comment] 2022-06-28 17:21
Yes, you are right. Good catch.
I have updated the master branch, and will issue a new release soon.
