### ISSUE TITLE
XLInternalError "Path does not exist in zip archive (xl/xl/worksheets/sheet1.xml"

### ISSUE THREAD

**Issue by Maginor** [troldal/OpenXLSX#306] opened 2024-12-13 17:01 UTC
I get this error when trying to open an xlsx file with the current commit of OpenXLSX. It did not happen with a version from june 2024, and the file also opens fine in Excel. The xlsx file is attached

```
	XLDocument doc;
	doc.open(std::string(file_name));

	auto wb = doc.workbook();
	auto n_tabs = wb.sheetCount();
	
	for(uint16_t tab = 1; tab <= n_tabs; ++tab) {
		
		try {
			auto basesheet = wb.sheet(tab);
			if(!basesheet.isType<XLWorksheet>())
				continue;
			
			auto sheet = basesheet.get<XLWorksheet>();
			
			//read_series_data_from_sheet(data_set, series, file_name, sheet, doc, tab);
			
		} catch (XLInternalError err) {
			//log_print("WARNING: In file ", file_name, " Unable to open sheet: ", err.what(), "\n");
			std::cout << "Unable to open sheet" << err.what();
			continue;
		}
	}

```
I encountered the same error both on Windows and Linux

[101_inputs.xlsx](https://github.com/user-attachments/files/18129139/101_inputs.xlsx)

**Comment by aral-matrix** [comment] 2024-12-15 00:39
Sorry about that, this is a side effect of https://github.com/troldal/OpenXLSX/commit/06453c0734781ee4893d256c550f550ae5f9fbba#diff-5e5f69e09f37b0db26e52c1545c003fbbdf544cbdcc537bb1f26c2f999beb489R333 - it's an easy fix except I am trying to remember why I introduced this change (it was to support some other document which had inconsistent document relationship paths, but I do not remember which issue this was), before I fix it - in order to ideally fix it in a way that doesn't break anything else.

**Comment by aral-matrix** [comment] 2024-12-15 00:43
Duplicate of #297

**Comment by aral-matrix** [comment] 2024-12-15 00:44
I just realized I have an open issue for this where I had a question back that never got answered. Thank you for providing the example file which allowed me to track down the actual bug & confirm the other issue.

**Comment by aral-matrix** [comment] 2024-12-15 02:43
Should be solved in the development-aral branch with https://github.com/troldal/OpenXLSX/commit/5dfa70a6e462cdaf6efe7758dde0957b3cab3970

**Comment by Maginor** [comment] 2024-12-15 08:53
Thank you for the quick reply!
If it is interesting, this was happening with xlsx files that were created using a pandas.ExcelWriter from the pandas python package.

**Comment by aral-matrix** [comment] 2024-12-15 12:13
Yes, thank you - that helps to confirm it's a duplicate of #297 - the author also mentioned the same library. I had adjusted the workbook relationships in the past to accept absolute paths to a worksheet, but broke it with the update on 29 July - I think I have it fixed properly now in a way that also allows global document relationships (in _rels/.rels) to begin with a leading slash or omit it (which seems to be the standard).

**Comment by Maginor** [comment] 2024-12-16 09:15
I can confirm that this fixed my problem

**Comment by aral-matrix** [comment] 2024-12-16 12:25
Glad to hear - I will close this issue when merging the patch into the main branch.

**Comment by aral-matrix** [comment] 2024-12-19 20:52
Patch has been merged into main branch. Closing as resolved.

**Closed by aral-matrix** 2024-12-19 20:52 UTC
Labels: bug, testing, resolved
