### ISSUE TITLE
Retrieving value from XLCellValueProxy reference segfaults in GCC but works in MSVC. Linter doesn't show errors.

### ISSUE THREAD

**Issue by arnabanimesh** [troldal/OpenXLSX#282] opened 2024-10-09 19:57 UTC
Different behavior between C++ compilers. Linter should show errors if type is wrong.

```cpp
#include <iostream>
#include <OpenXLSX.hpp>

int main()
{
    OpenXLSX::XLDocument doc;
    doc.open("input.xlsx");
    auto xl_sheet = doc.workbook().worksheet("Sample");
    // This below statement works as expected
    // OpenXLSX::XLCellValue cell_value = xl_sheet.cell(1, 1).value();
    // This below statement works fine in MSVC but segfaults in GCC (Tested in WSL2 Ubuntu 24.04 LTS). Linter doesn't show type errors.
    const auto &cell_value = xl_sheet.cell(1, 1).value();
    std::cout << cell_value.get<const char*>() << std::endl;
    doc.close();
    return 0;
}
```

**Comment by aral-matrix** [comment] 2024-10-10 21:10
You are creating a reference to a temporary object - the GCC compiler is warning about this:
```
Examples/Demo10.cpp: In function ‘int main()’:
Examples/Demo10.cpp:14:17: warning: possibly dangling reference to a temporary [-Wdangling-reference]
   14 |     const auto &cell_value = xl_sheet.cell(1, 1).value();
      |                 ^~~~~~~~~~
Examples/Demo10.cpp:14:55: note: the temporary was destroyed at the end of the full expression ‘OpenXLSX::XLWorksheet::cell(uint32_t, uint16_t) const(1, 1).OpenXLSX::XLCellAssignable::OpenXLSX::XLCell.OpenXLSX::XLCell::value()’
   14 |     const auto &cell_value = xl_sheet.cell(1, 1).value();
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

Why in this particular case auto resolves to XLCellValueProxy, I haven't yet had a look at.

However, as a general rule: you can not and should not create references to cells of the worksheet. The ```cell``` method of the XLWorksheet will create a temporary object that can be copy-assigned to an XLCell (or XLCellAssignable) object if you desire to use it repeatedly, or to which a value can be assigned, or whose value can be redirected to output.

In this case, if you remove the reference, you get an error that "XLCellValueProxy" is private within this context, and if you replace the ```auto``` with ```XLCellValue```, everything works as intended.

I agree that documentation eventually needs to guide the user a bit, but in general, the ```auto``` keyword is a false friend. Do not use it to let the compiler derive types for you when you do not know exactly what type it will be.

**Closed** 2024-10-10 22:08 UTC
