### ISSUE TITLE
OpenXLSX seems to ignore whitespaces

### ISSUE THREAD

**Issue by YoannNicod** [troldal/OpenXLSX#24] opened 2019-12-31 11:29 UTC
Hello, 

First of all, thank you for your work.
I think there is a problem with cells that contains only spaces. 
For instance, when I execute : 

    int main()
    {
        XLDocument doc;

        doc.CreateDocument("./t.xlsx");

        auto wks = doc.Workbook().Worksheet("Sheet1");

        wks.Cell(1, 1).Value() = "    ";

        doc.SaveDocument();
        doc.CloseDocument();

        return 0;
     }

The document created does not contain the spaces, whearas when I write "test" for example, it works.
I could also notice the problem when opening an existing document containing cells with only spaces and saving it right afterwards : the spaces disappear.

Thank you for your time.

**Comment by YoannNicod** [comment] 2019-12-31 11:34
Actually, it seems like spaces present before and after a text in a cell are removed :

wks.Cell(1, 1).Value() = "   Hello  World   ";

gives : "Hello  World"
instead of : "   Hello  World   "

**Comment by troldal** [comment] 2020-01-09 14:50
Hi @YoannNicod,

I'm happy you like it and I'm grateful for your input. It's not possible to come up with all possible use cases, so this kind of input is very useful.

It turns out that the string with leading/trailing whitespace is correctly stored in the .xlsx file in it's entirety. It is the Excel application that trims away leading and trailing whitespace. In order to retain the whitespace, an attribute has to b added to the relevant node in the underlying .xml file: xml:space="preserve". This will prevent Excel from trimming the whitespace away.

I have fixed this bug and updated the repository. Please check if it works out for you.

**Comment by Johnsik** [comment] 2020-02-05 09:51
Hello,  thanks for good work!

I have the similar problem.
When document loaded if cell contain only spaces it's marked as XLValueType::String but it length is 0.
The document was previously created by Excel and cell was saved with xml:space="preserve".

**Comment by troldal** [comment] 2020-02-12 15:41
Hi @Johnsik 

Sorry for the late reply and thank you for highlighting this issue. I looked into it and found that the issue is solved by setting different flags for the underlying PugiXML library.

I have updated the repo and it should now work as expected. Here is some sample code that works for me:

```cpp
#include <iostream>
#include <OpenXLSX/OpenXLSX.h>

using namespace std;
using namespace OpenXLSX;

int main() {

    XLDocument doc1;
    doc1.CreateDocument("./StringTest.xlsx");
    auto wks1 = doc1.Workbook().Worksheet("Sheet1");

    wks1.Cell("A1").Value() = "Hello OpenXLSX!";
    wks1.Cell("B1").Value() = " Hello OpenXLSX! ";
    wks1.Cell("C1").Value() = "  Hello OpenXLSX!  ";
    wks1.Cell("A2").Value() = "";
    wks1.Cell("B2").Value() = " ";
    wks1.Cell("C2").Value() = "  ";

    doc1.SaveDocument();
    doc1.CloseDocument();

    XLDocument doc2;
    doc2.OpenDocument("./StringTest.xlsx");
    auto wks2 = doc2.Workbook().Worksheet("Sheet1");

    cout << "Cell A1: " << wks2.Cell("A1").Value().Get<std::string>().length() << endl;
    cout << "Cell B1: " << wks2.Cell("B1").Value().Get<std::string>().length() << endl;
    cout << "Cell C1: " << wks2.Cell("C1").Value().Get<std::string>().length() << endl;
    cout << "Cell A2: " << wks2.Cell("A2").Value().Get<std::string>().length() << endl;
    cout << "Cell B2: " << wks2.Cell("B2").Value().Get<std::string>().length() << endl;
    cout << "Cell C2: " << wks2.Cell("C2").Value().Get<std::string>().length() << endl;

    doc2.CloseDocument();

    return 0;
}
```

The output is:
```
Cell A1: 15
Cell B1: 17
Cell C1: 19
Cell A2: 0
Cell B2: 1
Cell C2: 2

Process finished with exit code 0
```

Please let me know if it works for you.

**Comment by Johnsik** [comment] 2020-02-13 18:38
Thank you! Now it work properly!

**Closed** 2020-02-13 19:18 UTC
Labels: ready to close
